Реализация продюсера Задание 1
Alsadi1982/JavaSchool pull request #1
Opened 2024-12-24 14:07 UTC by Alsadi1982

2024-12-27 21:04 UTC, Liman26 requested changes

2024-12-27 21:04 UTC, Liman26 commented on pom.xml
> +            <version>2.2.6</version>
версии выносим в проперти

2024-12-27 21:04 UTC, Liman26 commented on src/main/java/sbp/school/kafka/Main.java
> +        TransactionEntity transaction1 = new TransactionEntity(OperationType.DEPOSITING, BigDecimal.valueOf(10000), 789456342);
тестовые/отладочные данные выносим в тесты

2024-12-27 21:04 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/TransactionService.java
> +        producer.flush();
Если произойдёт исключение и сервис упадёт, то сообщения последней пачки не будут отправлены и продюсер не будет закрыт, это надо делать в final методе

2025-01-16 18:23 UTC, Alsadi1982 commented on pom.xml
> +            <version>2.2.6</version>
поправил

2025-01-16 18:23 UTC, Alsadi1982 commented on src/main/java/sbp/school/kafka/service/TransactionService.java
> +        producer.flush();
поправил

2025-01-16 18:26 UTC, Alsadi1982 commented on src/main/java/sbp/school/kafka/Main.java
> +        TransactionEntity transaction1 = new TransactionEntity(OperationType.DEPOSITING, BigDecimal.valueOf(10000), 789456342);
поправил

2025-01-17 05:58 UTC, Liman26 approved these changes

2025-02-15 09:56 UTC, merged